name: Deploy Function

on:
  push:
    branches:
      - feature_01_supabase_setup
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_CONFIG: ${{ github.workspace }}/Sunaba/sunaba_bk/supabase/config.toml

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID